/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'AutoImport.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/AutoImport.story.vue')['default']
    BaseButton: typeof import('./../../../node_modules/@advjs/blender-ui/components/BaseButton.vue')['default']
    'BaseButton.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BaseButton.story.vue')['default']
    BCheckbox: typeof import('./../../../node_modules/@advjs/blender-ui/components/BCheckbox/BCheckbox.vue')['default']
    'BCheckbox.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BCheckbox/BCheckbox.story.vue')['default']
    BNumberField: typeof import('./../../../node_modules/@advjs/blender-ui/components/BNumberField/BNumberField.vue')['default']
    'BNumberField.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BNumberField/BNumberField.story.vue')['default']
    BPanel: typeof import('./../../../node_modules/@advjs/blender-ui/components/BPanel/BPanel.vue')['default']
    'BPanel.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BPanel/BPanel.story.vue')['default']
    BProperty: typeof import('./../../../node_modules/@advjs/blender-ui/components/BProperty/BProperty.vue')['default']
    'BProperty.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BProperty/BProperty.story.vue')['default']
    BSelectMenu: typeof import('./../../../node_modules/@advjs/blender-ui/components/BSelectMenu/BSelectMenu.vue')['default']
    'BSelectMenu.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BSelectMenu/BSelectMenu.story.vue')['default']
    BSelectOption: typeof import('./../../../node_modules/@advjs/blender-ui/components/BSelectMenu/BSelectOption.vue')['default']
    BSlider: typeof import('./../../../node_modules/@advjs/blender-ui/components/BSlider/BSlider.vue')['default']
    'BSlider.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BSlider/BSlider.story.vue')['default']
    BTextField: typeof import('./../../../node_modules/@advjs/blender-ui/components/BTextField/BTextField.vue')['default']
    'BTextField.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BTextField/BTextField.story.vue')['default']
    BTree: typeof import('./../../../node_modules/@advjs/blender-ui/components/BTree/BTree.vue')['default']
    'BTree.story': typeof import('./../../../node_modules/@advjs/blender-ui/components/BTree/BTree.story.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    Meow: typeof import('./../../../node_modules/@advjs/blender-ui/components/Meow.vue')['default']
    PainterColorPicker: typeof import('./../../../packages/controls/components/PainterColorPicker.vue')['default']
    PainterControls: typeof import('./../../../packages/controls/components/PainterControls.vue')['default']
    PainterIconButton: typeof import('./../../../packages/controls/components/PainterIconButton.vue')['default']
    PainterOptionsBar: typeof import('./../../../packages/controls/components/PainterOptionsBar.vue')['default']
    PainterSlider: typeof import('./../../../packages/controls/components/PainterSlider.vue')['default']
    PixiPainterApp: typeof import('./components/PixiPainterApp.vue')['default']
    README: typeof import('./../../../node_modules/@advjs/blender-ui/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
